-- Sample Tours Data for Touryaari Travels
-- 3-4 sample tours for testing purposes

-- Tour 1: Manali to Leh Road Trip
INSERT INTO public.tours (
    slug, title, subtitle, description, destination, location_detail, state, country,
    category, sub_category, duration_days, duration_nights,
    price_single, price_double, price_triple, price_quad,
    original_price, discount_percent, group_size_min, group_size_max, difficulty,
    thumbnail_url, gallery_images, itinerary, inclusions, exclusions, highlights,
    things_to_carry, faqs, activities, best_time, pickup_point,
    is_limited_seats, available_seats, is_featured, is_popular, is_active,
    rating, reviews_count, booking_policy, cancellation_policy,
    meta_title, meta_description
) VALUES (
    'manali-leh-road-trip',
    'Manali to Leh Road Trip',
    'The Ultimate Himalayan Adventure',
    '<p>Embark on the journey of a lifetime as you traverse the legendary Manali-Leh highway. Experience dramatic landscapes, high-altitude mountain passes, and the raw beauty of the Himalayas.</p><p>This 9-day adventure takes you through Rohtang Pass, Baralacha La, and the stunning More Plains before reaching the mystical land of Ladakh.</p>',
    'Leh Ladakh',
    'Manali - Keylong - Sarchu - Leh - Nubra - Pangong',
    'Himachal Pradesh & Ladakh',
    'India',
    'road-trip',
    'Himalayan Expedition',
    9,
    8,
    45000.00,
    38000.00,
    35000.00,
    32000.00,
    52000.00,
    13.00,
    6,
    15,
    'Challenging',
    'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?w=800',
    ARRAY['https://images.unsplash.com/photo-1563286094-8b90030e1d8a?w=800', 'https://images.unsplash.com/photo-1519883361061-b09e8d2f279f?w=800', 'https://images.unsplash.com/photo-1567581985473-135793525eec?w=800'],
    '[
        {"day": 1, "title": "Arrival in Manali", "description": "Welcome to Manali. Check-in, bike allocation, and briefing session.", "meals": ["Dinner"], "accommodation": "Hotel in Manali", "activities": ["Bike Check", "Briefing"]},
        {"day": 2, "title": "Manali to Jispa", "description": "Cross Rohtang Pass (3,978m) and enter Lahaul valley. Stay at Jispa.", "meals": ["Breakfast", "Dinner"], "accommodation": "Camp at Jispa", "activities": ["Rohtang Pass", "Lahaul Valley"]},
        {"day": 3, "title": "Jispa to Sarchu", "description": "Ride through Baralacha La (4,890m) and witness the stunning Suraj Tal.", "meals": ["Breakfast", "Dinner"], "accommodation": "Camp at Sarchu", "activities": ["Baralacha La", "Suraj Tal"]},
        {"day": 4, "title": "Sarchu to Leh", "description": "Cross Gata Loops, Nakee La, and Lachung La. Enter Ladakh.", "meals": ["Breakfast", "Dinner"], "accommodation": "Hotel in Leh", "activities": ["Gata Loops", "Nakee La"]},
        {"day": 5, "title": "Leh Local Sightseeing", "description": "Visit Shanti Stupa, Leh Palace, and explore the local markets.", "meals": ["Breakfast"], "accommodation": "Hotel in Leh", "activities": ["Shanti Stupa", "Leh Palace", "Market"]},
        {"day": 6, "title": "Leh to Nubra Valley", "description": "Cross Khardung La (5,359m), one of the highest motorable passes.", "meals": ["Breakfast", "Dinner"], "accommodation": "Camp in Nubra", "activities": ["Khardung La", "Diskit Monastery", "Hunder Sand Dunes"]},
        {"day": 7, "title": "Nubra to Pangong Lake", "description": "Ride to the magical Pangong Lake via Shyok route.", "meals": ["Breakfast", "Dinner"], "accommodation": "Camp at Pangong", "activities": ["Pangong Lake", "Sunset"]},
        {"day": 8, "title": "Pangong to Leh", "description": "Return to Leh via Chang La pass. Celebrate your journey.", "meals": ["Breakfast", "Dinner"], "accommodation": "Hotel in Leh", "activities": ["Chang La", "Farewell Dinner"]},
        {"day": 9, "title": "Departure", "description": "Check-out and transfer to airport for your onward journey.", "meals": ["Breakfast"], "accommodation": "N/A", "activities": ["Airport Transfer"]}
    ]'::jsonb,
    ARRAY['Royal Enfield 350cc/500cc with fuel', 'Experienced road captain', 'Backup vehicle with mechanic', 'All accommodations on twin sharing', 'Meals as per itinerary', 'Inner line permits', 'Medical kit and oxygen cylinder', 'Touryaari Travels merchandise'],
    ARRAY['Flights to/from Manali/Leh', 'Personal expenses', 'Any damage to bike due to rider negligence', 'Travel insurance', 'Tips and gratitude'],
    ARRAY['World''s highest motorable passes', 'Ride through Gata Loops (21 hairpin bends)', 'Camp at Pangong Lake', 'Bactrian camel ride in Nubra', 'Professional photography support'],
    ARRAY['Thermal innerwear', 'Riding jacket and pants', 'Waterproof gloves', 'Sunscreen SPF 50+', 'Sunglasses with UV protection', 'Personal medicines', 'Water bottle and hydration pack'],
    '[
        {"question": "Do I need prior riding experience?", "answer": "Yes, at least 2 years of riding experience is required for this challenging terrain."},
        {"question": "What if the pass is closed due to weather?", "answer": "Touryaari Travels will arrange alternative routes or wait for clearance. Safety first always."},
        {"question": "Is altitude sickness common?", "answer": "Yes, we acclimatize properly and carry medical oxygen. Follow the road captain''s instructions."}
    ]'::jsonb,
    ARRAY['Motorcycling', 'Camping', 'Photography', 'Stargazing', 'Cultural Tours'],
    'June to September',
    'Manali Bus Stand',
    true,
    12,
    true,
    true,
    true,
    4.8,
    156,
    'Full payment required 15 days before departure. Cancellation policy applies.',
    '50% refund if cancelled 30 days before departure. No refund within 15 days of departure.',
    'Manali Leh Road Trip 2024 | Bike Expedition - Touryaari Travels',
    'Join the ultimate Manali to Leh bike trip. 9 days of adventure across 5 high-altitude passes. Book now with Touryaari Travels.'
);

-- Tour 2: Kedarnath Yatra
INSERT INTO public.tours (
    slug, title, subtitle, description, destination, location_detail, state, country,
    category, sub_category, duration_days, duration_nights,
    price_single, price_double, price_triple, price_quad,
    original_price, discount_percent, group_size_min, group_size_max, difficulty,
    thumbnail_url, gallery_images, itinerary, inclusions, exclusions, highlights,
    things_to_carry, faqs, activities, best_time, pickup_point,
    is_limited_seats, available_seats, is_featured, is_popular, is_active,
    rating, reviews_count, booking_policy, cancellation_policy,
    meta_title, meta_description
) VALUES (
    'kedarnath-yatra',
    'Kedarnath Yatra',
    'Sacred Journey to Lord Shiva''s Abode',
    '<p>Embark on a divine journey to one of the twelve Jyotirlingas and the most important among the Panch Kedar. The Kedarnath Temple stands magnificently at 3,583 meters, surrounded by snow-capped peaks.</p>',
    'Kedarnath',
    'Haridwar - Guptkashi - Kedarnath - Rishikesh',
    'Uttarakhand',
    'India',
    'spiritual',
    'Char Dham',
    5,
    4,
    18500.00,
    15500.00,
    14000.00,
    13000.00,
    22000.00,
    16.00,
    4,
    20,
    'Moderate',
    'https://images.unsplash.com/photo-1595814433015-e6f5ce69614e?w=800',
    ARRAY['https://images.unsplash.com/photo-1589998339597-547767246d53?w=800', 'https://images.unsplash.com/photo-1623662324287-9d1358403c94?w=800'],
    '[
        {"day": 1, "title": "Haridwar to Guptkashi", "description": "Pick-up from Haridwar railway station. Drive to Guptkashi (8 hrs).", "meals": ["Breakfast", "Dinner"], "accommodation": "Hotel in Guptkashi", "activities": ["Ganga Aarti at Haridwar"]},
        {"day": 2, "title": "Gaurikund to Kedarnath", "description": "Drive to Gaurikund, then 16km trek to Kedarnath Temple.", "meals": ["Breakfast", "Dinner"], "accommodation": "Guest House near Temple", "activities": ["Trekking", "Temple Darshan"]},
        {"day": 3, "title": "Kedarnath to Guptkashi", "description": "Morning darshan and trek back to Gaurikund. Drive to Guptkashi.", "meals": ["Breakfast", "Dinner"], "accommodation": "Hotel in Guptkashi", "activities": ["Morning Aarti", "Trek Down"]},
        {"day": 4, "title": "Guptkashi to Rishikesh", "description": "Drive to Rishikesh via Devprayag. Evening Ganga Aarti.", "meals": ["Breakfast", "Dinner"], "accommodation": "Hotel in Rishikesh", "activities": ["Devprayag", "Triveni Ghat Aarti"]},
        {"day": 5, "title": "Departure", "description": "Drop at Haridwar railway station.", "meals": ["Breakfast"], "accommodation": "N/A", "activities": []}
    ]'::jsonb,
    ARRAY['AC vehicle for transfers', 'Hotel accommodations', 'Vegetarian meals', 'Pony/Palki assistance for Kedarnath trek', 'Experienced tour manager', 'Temple special darshan assistance'],
    ARRAY['Flights/Train to Haridwar', 'Helicopter charges (optional)', 'Personal expenses'],
    ARRAY['Darshan at ancient Kedarnath Temple', 'Witness the confluence at Devprayag', 'Ganga Aarti at Haridwar & Rishikesh', 'Scenic drive along the Ganges'],
    ARRAY['Warm clothing', 'Rain jacket', 'Comfortable trekking shoes', 'Personal medicines', 'Torch', 'Water bottle'],
    '[
        {"question": "Is the trek difficult?", "answer": "The 16km trek is moderate. Pony and palki services are available for those who need assistance."},
        {"question": "What is the best time to visit?", "answer": "May to June and September to October are ideal for the yatra."},
        {"question": "Are there medical facilities?", "answer": "Basic medical facilities are available. We carry a first aid kit."}
    ]'::jsonb,
    ARRAY['Pilgrimage', 'Trekking', 'Temple Visits'],
    'May to June, September to October',
    'Haridwar Railway Station',
    true,
    18,
    true,
    true,
    true,
    4.9,
    243,
    'Full payment required 10 days before departure.',
    '75% refund if cancelled 20 days before departure. 50% refund within 10-20 days. No refund within 10 days.',
    'Kedarnath Yatra 2024 | Sacred Pilgrimage - Touryaari Travels',
    'Join the sacred Kedarnath Yatra with Touryaari Travels. 5 days of divine journey to Lord Shiva''s abode.'
);

-- Tour 3: Kasol & Manikaran Weekend
INSERT INTO public.tours (
    slug, title, subtitle, description, destination, location_detail, state, country,
    category, sub_category, duration_days, duration_nights,
    price_single, price_double, price_triple, price_quad,
    original_price, discount_percent, group_size_min, group_size_max, difficulty,
    thumbnail_url, gallery_images, inclusions, exclusions, highlights,
    activities, best_time, pickup_point,
    is_limited_seats, available_seats, is_featured, is_popular, is_active,
    rating, reviews_count, booking_policy, cancellation_policy,
    meta_title, meta_description
) VALUES (
    'kasol-manikaran-weekend',
    'Kasol & Manikaran Weekend',
    'Hippie Paradise & Hot Springs',
    '<p>Escape to the Parvati Valley for a relaxing weekend in Kasol, known as Mini Israel of India. Visit Manikaran for its hot springs and gurudwara.</p>',
    'Kasol',
    'Delhi - Kasol - Manikaran - Tosh',
    'Himachal Pradesh',
    'India',
    'weekend',
    'Himalayan Getaway',
    3,
    2,
    8500.00,
    7500.00,
    7000.00,
    6500.00,
    9500.00,
    11.00,
    6,
    20,
    'Easy',
    'https://images.unsplash.com/photo-1626010448982-9d629c1eb465?w=800',
    ARRAY['https://images.unsplash.com/photo-1605648916319-cf082f7524a1?w=800', 'https://images.unsplash.com/photo-1589519160732-57fc498494f8?w=800'],
    ARRAY['AC Volvo bus transfers', 'Hotel accommodation', 'Meals as per itinerary', 'Tour guide', 'Sightseeing'],
    ARRAY['Personal expenses', 'Meals not mentioned in itinerary', 'Travel insurance'],
    ARRAY['Relax in Parvati Valley', 'Visit Manikaran hot springs', 'Explore Israeli cafes', 'Trek to Tosh village'],
    ARRAY['Trekking', 'Café Hopping', 'Hot Springs', 'Shopping'],
    'March to June, September to November',
    'Delhi ISBT Kashmere Gate',
    false,
    0,
    true,
    true,
    true,
    4.6,
    89,
    'Full payment required 7 days before departure.',
    '50% refund if cancelled 7 days before departure. No refund within 7 days.',
    'Kasol Manikaran Weekend Trip 2024 - Touryaari Travels',
    'Escape to Kasol for a relaxing weekend. Visit Manikaran hot springs and explore Parvati Valley with Touryaari Travels.'
);

-- Tour 4: Bhutan - The Land of Happiness
INSERT INTO public.tours (
    slug, title, subtitle, description, destination, location_detail, state, country,
    category, sub_category, duration_days, duration_nights,
    price_single, price_double, price_triple, price_quad,
    original_price, discount_percent, group_size_min, group_size_max, difficulty,
    thumbnail_url, gallery_images, itinerary, inclusions, exclusions, highlights,
    things_to_carry, faqs, activities, best_time, pickup_point,
    is_limited_seats, available_seats, is_featured, is_popular, is_active,
    rating, reviews_count, booking_policy, cancellation_policy,
    meta_title, meta_description
) VALUES (
    'bhutan-happiness-tour',
    'Bhutan - The Land of Happiness',
    'Explore the World''s Only Carbon Negative Country',
    '<p>Discover the mystical kingdom of Bhutan where Gross National Happiness is more important than GDP. Visit ancient dzongs, monasteries, and experience pristine Himalayan culture.</p>',
    'Bhutan',
    'Paro - Thimphu - Punakha - Paro',
    NULL,
    'Bhutan',
    'international',
    'Himalayan Kingdom',
    6,
    5,
    85000.00,
    75000.00,
    70000.00,
    65000.00,
    95000.00,
    11.00,
    4,
    12,
    'Easy',
    'https://images.unsplash.com/photo-1572938546064-07c6a1d87066?w=800',
    ARRAY['https://images.unsplash.com/photo-1563264957-371018c33d07?w=800', 'https://images.unsplash.com/photo-1544139731-495d596e8b81?w=800'],
    '[
        {"day": 1, "title": "Arrival in Paro", "description": "Fly into Paro. Visit Rinpung Dzong and National Museum.", "meals": ["Breakfast", "Dinner"], "accommodation": "Hotel in Paro", "activities": ["Paro Dzong", "National Museum"]},
        {"day": 2, "title": "Paro to Thimphu", "description": "Drive to capital city. Visit Tashichho Dzong and Buddha Point.", "meals": ["Breakfast", "Dinner"], "accommodation": "Hotel in Thimphu", "activities": ["Buddha Dordenma", "Tashichho Dzong"]},
        {"day": 3, "title": "Thimphu Local", "description": "Visit National Memorial Chorten, Textile Museum, and Folk Heritage Museum.", "meals": ["Breakfast", "Dinner"], "accommodation": "Hotel in Thimphu", "activities": ["Chorten", "Local Markets"]},
        {"day": 4, "title": "Thimphu to Punakha", "description": "Cross Dochula Pass. Visit Punakha Dzong and Suspension Bridge.", "meals": ["Breakfast", "Dinner"], "accommodation": "Hotel in Punakha", "activities": ["Dochula Pass", "Punakha Dzong"]},
        {"day": 5, "title": "Punakha to Paro", "description": "Return to Paro. Hike to Tiger''s Nest Monastery (Taktsang).", "meals": ["Breakfast", "Dinner"], "accommodation": "Hotel in Paro", "activities": ["Tiger''s Nest Hike"]},
        {"day": 6, "title": "Departure", "description": "Transfer to Paro airport.", "meals": ["Breakfast"], "accommodation": "N/A", "activities": []}
    ]'::jsonb,
    ARRAY['Bhutan visa and permit', 'Licensed Bhutanese guide', '3-star accommodation', 'All meals (breakfast, lunch, dinner)', 'Private transport', 'Tiger''s Nest permit', 'Touryaari Travels tour manager'],
    ARRAY['Flights to/from Paro', 'Travel insurance', 'Personal expenses', 'Tips'],
    ARRAY['Tiger''s Nest Monastery hike', 'Visit to Punakha Dzong', 'Cross Dochula Pass (3,100m)', 'Experience Bhutanese culture'],
    ARRAY['Comfortable walking shoes', 'Warm clothing', 'Sunscreen', 'Sunglasses', 'Personal medicines', 'Camera'],
    '[
        {"question": "Do I need a visa for Bhutan?", "answer": "Touryaari Travels will arrange your Bhutan visa and permits as part of the package."},
        {"question": "Is the Tiger''s Nest hike difficult?", "answer": "The hike is moderate and takes about 4-5 hours. Ponies are available for part of the way."},
        {"question": "What currency is used in Bhutan?", "answer": "Bhutan uses Ngultrum (BTN) which is pegged to Indian Rupee. INR is widely accepted."}
    ]'::jsonb,
    ARRAY['Cultural Tours', 'Hiking', 'Photography', 'Architecture'],
    'March to May, September to November',
    'Paro International Airport',
    true,
    8,
    true,
    true,
    true,
    4.9,
    127,
    'Full payment required 30 days before departure due to visa processing.',
    '50% refund if cancelled 30 days before departure. No refund within 30 days due to visa costs.',
    'Bhutan Tour 2024 | Land of Happiness - Touryaari Travels',
    'Discover Bhutan with Touryaari Travels. Visit Tiger''s Nest, experience Gross National Happiness, and explore the mystical kingdom.'
);
