-- Test query to check if tours exist in database
SELECT id, slug, title, is_popular, is_active FROM public.tours;

-- If no results, insert sample tours
INSERT INTO public.tours (
    slug, title, subtitle, description, destination, location_detail, state, country,
    category, sub_category, duration_days, duration_nights,
    price_single, price_double, price_triple, price_quad,
    original_price, discount_percent, group_size_min, group_size_max, difficulty,
    thumbnail_url, gallery_images, itinerary, inclusions, exclusions, highlights,
    things_to_carry, faqs, activities, best_time, pickup_point,
    is_limited_seats, available_seats, is_featured, is_popular, is_active,
    rating, reviews_count, booking_policy, cancellation_policy,
    meta_title, meta_description
) VALUES (
    'manali-leh-road-trip',
    'Manali to Leh Road Trip',
    'The Ultimate Himalayan Adventure',
    '<p>Embark on the journey of a lifetime as you traverse the legendary Manali-Leh highway.</p>',
    'Leh Ladakh',
    'Manali - Keylong - Sarchu - Leh - Nubra - Pangong',
    'Himachal Pradesh & Ladakh',
    'India',
    'road-trip',
    'Himalayan Expedition',
    9,
    8,
    45000.00,
    38000.00,
    35000.00,
    32000.00,
    52000.00,
    13.00,
    6,
    15,
    'Challenging',
    'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?w=800',
    ARRAY['https://images.unsplash.com/photo-1563286094-8b90030e1d8a?w=800'],
    '[]'::jsonb,
    ARRAY['Royal Enfield with fuel', 'Experienced road captain', 'All accommodations'],
    ARRAY['Flights', 'Personal expenses'],
    ARRAY['World''s highest motorable passes', 'Camp at Pangong Lake'],
    ARRAY['Thermal innerwear', 'Riding jacket'],
    '[]'::jsonb,
    ARRAY['Motorcycling', 'Camping'],
    'June to September',
    'Manali Bus Stand',
    true,
    12,
    true,
    true,
    true,
    4.8,
    156,
    'Full payment required 15 days before departure.',
    '50% refund if cancelled 30 days before departure.',
    'Manali Leh Road Trip 2024 - Touryaari Travels',
    'Join the ultimate Manali to Leh bike trip.'
);
